In [1]:
import pandas as pd
import numpy as np


In [ ]:
# Тип данных и их изменение. Замена индекса и количество элементов должно совпабать.
# Series - Серрия создание.
# data: - Список или словарь
# index: - должен совпадать с data
# dtype: - Тип данных в солбца - Позволяет изменить тип данных.
# name: Hashable = ...,
# copy: bool = ...
#
series_from_list = pd.Series(
    [1, 2, 3, 4],
    index=["row1", "row2", "row3", "row4"],
    dtype="string"
)
series_from_list

row1    1
row2    2
row3    3
row4    4
dtype: string

In [ ]:
# Список на основе словаря. на основе словаря мы делаем выборк.
dict_array = {"row1": 1, "row2": 2, "row3": 3, "row4": 4}

series_from_list = pd.Series(
    dict_array, # Список
    index=["row1", "row2", "row100"], # Выборка из словаря
    dtype=int # Изменение типа данных
    )
series_from_list

row1      1.0
row2      2.0
row100    NaN
dtype: float64

In [ ]:
# Массив Numpy и изменение Данных copy=False
np_array = np.array([5, 6, 7, 8, 9])


def series_copy_false(n: np.array):
    """
    copy=False - Изменяет оригенал
    copy=True - Не изменяет оригина делает его копию"""

    s = pd.Series(n, copy=False)
    return s


ser_np_arr = series_copy_false(np_array)

# copy=False В серре значение будет изенено + оригинал.
ser_np_arr.iloc[3] = 111

print(ser_np_arr)
print(np_array)

0      5
1      6
2      7
3    111
4      9
dtype: int64
[  5   6   7 111   9]


In [6]:
# Series на основание другой series
series_from_list = pd.Series(
    [50, 66, 9.0, 1, 77, 00],
    index=["row_1", "row_2", "row_3", "row_4", "row_5", "row_6"],
    dtype="string",
)
print(series_from_list)


def ser_from_ser(s: pd.Series):
    """
    Работает так как еслибы передали словарь
    index=[ - Взяты нужные данные"""
    res = pd.Series(s, index=["row_1", "row_5", "row_3"])
    return res


print(ser_from_ser(series_from_list))


row_1     50
row_2     66
row_3    9.0
row_4      1
row_5     77
row_6      0
dtype: string
row_1     50
row_5     77
row_3    9.0
dtype: string


In [ ]:
# --DataFrame
# Data - Данные которые мы хотим передать в виде Объекта.
# index - (по умолчанию Rengelndex) список элиментов которого будут использоваться в качестве индекса строк.
# columns - список меток столбцов.
# dtype -
# copy -

In [8]:
# В словаре должно быть равное колличество ЭЛЕМЕНТОВ.
# Ключи это метки столбцов
dict_array = {
    "col_1": [5, 6, 6, 3, 7],
    "col_2": [27, 6, 7, 4, 7],
    "col_3": [1, 45, 6, 62, 7],
    "col_4": [65, 6, 7, 82, 7],
    "col_5": [8, 3, 2, 5, 1],
}


In [3]:
list_arr = [{
    "col_1": [5, 6, 6, 3, 7],
    "col_2": [27, 6, 7, 4, 7],
    "col_3": [1, 45, 6, 62, 7],
    "col_4": [65, 6, 7, 82, 7],
    "col_5": [8, 3, 2, 5, 1],
}]

df_l = pd.DataFrame(list_arr)

df_l

col_1             col_2              col_3              col_4  \
0  [5, 6, 6, 3, 7]  [27, 6, 7, 4, 7]  [1, 45, 6, 62, 7]  [65, 6, 7, 82, 7]   

             col_5  
0  [8, 3, 2, 5, 1]

In [ ]:
# DataFrame на оснавание словаря.
# index=[] - Будут заменены. индексы долзны соответствовать количеству словарю.
# columns - Делаем Выборку. В словаре Ключи это метки столбцов
# dtype=float - Изменение типа банны
df = pd.DataFrame(
    dict_array,
    index=["row_1", "row_2", "row_3", "row_4", "row_5"],
    # columns=["col_4", "col_1", "5"],
    dtype=float,
)

# df.iloc[0].tolist() - Возвращает первую строку в виде списка
# .tolist() превращает её в список.
row_0 = df.iloc[0].tolist()
print(row_0)


[5.0, 27.0, 1.0, 65.0, 8.0]


In [ ]:
# DataFrame на соснование массива Numpy
np_array = np.array(
    [
        [5, 6, 6, 3, 7],
        [27, 6, 7, 4, 7],
        [1, 45, 6, 62, 7],
        [65, 6, 7, 82, 7],
        [8, 3, 2, 5, 1],
    ]
)


# np_array
def df_copy(n: np.array):
    """
    copy=True - Изменения только в dataFrame
    copy=False - Используем сам массив Numpy а не его копию"""
    ret = pd.DataFrame(n, copy=True)
    return ret


df_1 = df_copy(np_array)
# Скопирован и изменен.
df_1.loc[:, 3:4] = 10011
print(df_1)

# В массиве Numpy нет изменений
print(np_array)

    0   1  2      3      4
0   5   6  6  10011  10011
1  27   6  7  10011  10011
2   1  45  6  10011  10011
3  65   6  7  10011  10011
4   8   3  2  10011  10011
[[ 5  6  6  3  7]
 [27  6  7  4  7]
 [ 1 45  6 62  7]
 [65  6  7 82  7]
 [ 8  3  2  5  1]]


In [ ]:
# Выравнивание Индексов.
dict_array = {"row_1": 2, "row_2": 3, "row_3": 4, "row_4": 5, "row_5": 6}


df = pd.DataFrame(
    {"col_1": pd.Series(dict_array), "col_2": [5, 6, 6, np.nan, 7]},
    index=["row_1", "row_2", "row_5", "row_6", "row_9"],
)
df

col_1  col_2
row_1    2.0    5.0
row_2    3.0    6.0
row_5    6.0    6.0
row_6    NaN    NaN
row_9    NaN    7.0

In [ ]:
# Выравнивание Индексов.
dict_array = {"row_1": 2, "row_2": 3, "row_3": 4, "row_4": 5, "row_5": 6}

# Пересечений индексов. Обединение СЕРИИ. Выборка индексов
df = pd.DataFrame(
    {
        "col_1": pd.Series(dict_array),
        "col_2": pd.Series(
            [5, 6, 6, np.nan, 7], index=["row_3", "row_4", "row_5", "row_6", "row_9"]
        ),
    },
    #   index=['row_1', 'row_7']
)
df

col_1  col_2
row_1    2.0    NaN
row_2    3.0    NaN
row_3    4.0    5.0
row_4    5.0    6.0
row_5    6.0    6.0
row_6    NaN    NaN
row_9    NaN    7.0

In [56]:
import pandas as pd

df = pd.DataFrame(
    {
        "A": [1, 2, 3],
        "B": ["a", "b", "c"],
        "C": [4.1, 5.2, 6.3],
        "D": [True, False, True],
    }
)


def row_list():
    """
    (df[['A','B','C','D']] == row_list) → сравнивает каждую строку с элементами списка.
    .all(axis=1) → проверяет, что все значения совпали по колонкам.
    mask — булев столбец, где True означает полное совпадение.
    df[mask] — возвращает строки, где все значения совпадают.
    """

    # row_list = [1, 'a', 4.1, True]
    row_list_0 = df.iloc[0].tolist()

    # Сравнение по всем колонкам
    mask = (df[["A", "B", "C", "D"]] == row_list_0).all(axis=1)
    print(df[mask])
    print(mask, "Тут комент херня есть совпадения на 0 индексе")


if __name__ == "__main__":
    row_list()


   A  B    C     D
0  1  a  4.1  True
0     True
1    False
2    False
dtype: bool Тут комент херня есть совпадения на 0 индексе


In [ ]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['a', 'b', 'c'],
    'C': [4.1, 5.2, 6.3],
    'D': [True, False, True]
})

def row_value_list():
    """
    .values.tolist() превращает весь датафрейм в обычный список списков.
    Операция row_list in all_rows проверяет, есть ли точное совпадение.
    all_rows.index(row_list) возвращает индекс первой совпавшей строки.
    Работает быстрее и проще, чем булева маска, особенно если нужно лишь проверить наличие совпадения.
    """
    row_list = [1, 'a', 4.1, True]

    # Преобразуем DataFrame в список списков
    all_rows = df.values.tolist()

    # Проверка на совпадение
    if row_list in all_rows:
        print("Совпадение найдено ✅")
        # Получим индекс строки
        index = all_rows.index(row_list)
        print(f"Индекс совпадающей строки: {index}")
    else:
        print("Совпадений нет ❌")


Совпадение найдено ✅
Индекс совпадающей строки: 0
